//
//  DeveloperPreview.swift
//  Aconchego
//
//  Created by Thiago Ogawa on 10/10/25.
//
import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberfOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 567,
            latitude: 25.7860,
            longitude: -80.1936,
            imageURLs: ["german-1", "german-2"],
            address: "124 Main St",
            city: "Rothenburg ob der Tauber",
            state: "Germany",
            title: "Medieval Jewel of Bavaria",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberfOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 567,
            latitude: 25.7760,
            longitude: -80.1340,
            imageURLs: ["austria-2", "austria-1", "austria-3"],
            address: "124 Main St",
            city: "Miami",
            state: "Florida",
            title: "Miami Beach House",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .tv, .kitchen, .office],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Steve Johnson",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberfOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 567,
            latitude: 25.7650,
            longitude: -80.1936,
            imageURLs: ["listing-2", "listing-1", "listing-3", "listing-4"],
            address: "124 Main St",
            city: "Miami",
            state: "Florida",
            title: "Beautiful Miami apartment in downtown Brickell",
            rating: 4.32,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Harry Styles",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberfOfGuests: 4,
            numberOfBeds: 4,
            pricePerNight: 763,
            latitude: 34.2,
            longitude: -118.0426,
            imageURLs: ["listing-2", "listing-1", "listing-3", "listing-4"],
            address: "124 Main St",
            city: "Los Angeles",
            state: "California",
            title: "Beautiful Los Angeles home in Malibu",
            rating: 4.97,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .pool],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Emily Davis",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberfOfGuests: 3,
            numberOfBeds: 2,
            pricePerNight: 210,
            latitude: 37.7749,
            longitude: -122.4194,
            imageURLs: ["listing-5", "listing-6", "listing-7"],
            address: "567 Castro St",
            city: "San Francisco",
            state: "California",
            title: "Cozy apartment in downtown San Francisco",
            rating: 4.71,
            features: [.selfCheckIn],
            amenities: [.wifi, .tv, .kitchen],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Carlos Mendes",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 5,
            numberOfBathrooms: 4,
            numberfOfGuests: 8,
            numberOfBeds: 6,
            pricePerNight: 890,
            latitude: 40.7128,
            longitude: -74.0060,
            imageURLs: ["listing-8", "listing-9", "listing-10"],
            address: "22 Wall St",
            city: "New York",
            state: "New York",
            title: "Luxury penthouse in Manhattan",
            rating: 4.95,
            features: [.superHost],
            amenities: [.wifi, .office, .laundry, .tv, .kitchen],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Anna Brown",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberfOfGuests: 5,
            numberOfBeds: 3,
            pricePerNight: 310,
            latitude: 47.6062,
            longitude: -122.3321,
            imageURLs: ["listing-11", "listing-12", "listing-13"],
            address: "98 Pine St",
            city: "Seattle",
            state: "Washington",
            title: "Modern home with ocean view in Seattle",
            rating: 4.82,
            features: [.selfCheckIn],
            amenities: [.wifi, .balcony, .kitchen, .laundry],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Lucas Ferreira",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 2,
            numberOfBathrooms: 2,
            numberfOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 250,
            latitude: -23.5505,
            longitude: -46.6333,
            imageURLs: ["listing-14", "listing-15", "listing-16"],
            address: "Rua Augusta, 2300",
            city: "São Paulo",
            state: "São Paulo",
            title: "Stylish loft in São Paulo downtown",
            rating: 4.67,
            features: [.selfCheckIn],
            amenities: [.wifi, .tv, .office],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sophia Miller",
            ownerImageUrl: "female-profile-photo",
            numberOfBedrooms: 6,
            numberOfBathrooms: 5,
            numberfOfGuests: 10,
            numberOfBeds: 8,
            pricePerNight: 1250,
            latitude: 48.8566,
            longitude: 2.3522,
            imageURLs: ["listing-17", "listing-18", "listing-19"],
            address: "45 Rue de Rivoli",
            city: "Paris",
            state: "Île-de-France",
            title: "Elegant Parisian mansion near the Louvre",
            rating: 4.98,
            features: [.superHost],
            amenities: [.wifi, .alarmSystem, .pool, .balcony, .laundry],
            type: .villa
        )
    ]
}
